### ISSUE TITLE
Add-on for Firefox on Android

### ISSUE THREAD

**Issue by jancborchardt** [tosdr/tosdr-firefox#13]
Since more and more people use mobile devices to browse the web, it would be really cool to also have the add-on work with Firefox for Android tablets and smartphones: https://addons.mozilla.org/en-US/android/

Is it possible to make this addon compatible or do we have to develop a separate one?

cc @AbdullahDiaa @freaktechnik @hugoroy @michielbdejong

**Comment by AbdullahDiaa** [comment]
clsoed until better support of WebExtensions for android is available
