### ISSUE TITLE
Documentation of add-on behaviour is lacking

### ISSUE THREAD

**Issue by simplypeachy** [tosdr/tosdr-firefox#32]
Hi, ToS;DR seems like a great idea and I'd love to take advantage of the FireFox add-on. I am a privacy-conscious web user and I would like to know how ToS;DR tells me the details of the ToS for a given web site. Questions, which I would have thought other prospective users would ask are:
Does the add-on send the site address to ToS;DR?
Does this happen for every web site I visit?
Does it send the entire URL, including parameters?
What other information is sent to ToS;DR, if any?
Does this information get sent securely?
What does ToS;DR retain from this request?
How does the behaviour of the toolbar change when in Private Browsing mode?

With tongue firmly in cheek...I suggest the add-on may need a ToS :-D
I did look here and on the ToS;DR web site for specific information regarding this and couldn't find any, so if I'm asking FAQs that are already answered then maybe they need more prominence.

**Comment by AbdullahDiaa** [comment]
**Does the add-on send the site address to ToS;DR?**
The addon will first retrieve [a list of services](https://tosdr.org/index/services.json) enlisted in ToS;DR then store it locally, then it'll match "base domain e.g. *google.com*" against that locally stored array and only if the domain is there, it'll query its details from tosdr.org.

[Request to get list of services](https://github.com/tosdr/tosdr-firefox/blob/1dadbb65f8c7803e794136dc2b8e43775d6c466f/lib/service/service.js#L15) => https://tosdr.org/index/services.json
**Params**: -

[Request to get service details](https://github.com/tosdr/tosdr-firefox/blob/1dadbb65f8c7803e794136dc2b8e43775d6c466f/lib/service/service.js#L34) => https://tosdr.org/services/google.json
**Params**: "Base domain in URL"

[Request to get point details](https://github.com/tosdr/tosdr-firefox/blob/6ba731e9cd97fdfbf1b727655666c2a8497a55a1/lib/service/point.js#L16) => https://tosdr.org/points/4738ex5PI1g.json
**Params**: "Point id in URL"

-
**Does this happen for every web site I visit?** 
Yep, it'll match base domain locally on every tab/URL change.
https://github.com/tosdr/tosdr-firefox/blob/f9bbe73a5fdf8998a78a67be74d40ab465e34117/lib/tos-notifications.js#L48

-
**Does it send the entire URL, including parameters?** 
Only base domain of websites listed on ToS;DR is sent:
https://github.com/tosdr/tosdr-firefox/blob/f9bbe73a5fdf8998a78a67be74d40ab465e34117/lib/utils/tld.js#L30

-
**What other information is sent to ToS;DR, if any?** 
No other information sent to ToS;DR servers.

-
**Does this information get sent securely?** 
Yep, all request are secure over HTTPS.
https://github.com/tosdr/tosdr-firefox/blob/9a72252025fd4da09122c56b0db0a7149d72cefb/lib/utils/service.js#L4

-
**What does ToS;DR retain from this request?** 
Updated Rating data.

-
**How does the behaviour of the toolbar change when in Private Browsing mode?** 
It won't work in private browsing mode.

-

**Comment by simplypeachy** [comment]
Thanks for such a prompt and detailed reply.
