### ISSUE TITLE
Lots of performance alerts

### ISSUE THREAD

**Issue by Yoric** [tosdr/tosdr-firefox#33]
For the past few weeks, ToSDR add-on has caused numerous CPOW performance alerts on Firefox Nightly (with e10s enabled).

On my machine, histogram `MISBEHAVING_ADDONS_CPOW_TIME_MS` for ToSDR reads as follows:

```
jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack
1298 samples, average = 4196.2, sum = 5446680

    8 |  0
   13 |  7
   37 |  1
  103 |  1
  171 |#####  81
  284 |  2
  472 |####  63
  785 |##  36
 1306 |########  124
 2172 |##############  220
 3613 |#########################  395
 6011 |#######################  368
10000 |  0
```

I believe that some of it is due to a performance regression inside Firefox, but ideally, this add-on should avoid CPOWs entirely.

**Comment by hugoroy** [comment]
Thanks for the report. @AbdullahDiaa do you have any idea?

**Comment by AbdullahDiaa** [comment]
@hugoroy I'm investigating the problem right now.

**Comment by AbdullahDiaa** [comment]
We've migrated to webextensions 
https://addons.mozilla.org/en-US/firefox/addon/terms-of-service-didnt-read/versions/beta
