### ISSUE TITLE
Upstream urlbutton.js changes

### ISSUE THREAD

**Issue by BigBlueHat** [tosdr/tosdr-firefox#34]
It seems this project contains a fork of `urlbutton.js` from this project:
https://github.com/voxpelli/moz-urlbarbutton/

The copy here includes some changes to make it compatible with the new `jpm` tool.

Could you be up to considering upstreaming those changes to @voxpelli's project? Eventually, it'd be great to have `moz-urlbutton` on npm for all to use. :smile: 

Thanks for considering this!

**Comment by voxpelli** [comment]
Would love that – especially any `jpm`-related changes as I haven't yet gotten around to any of that. Also – cool that this project found use for my addon-modules, had no idea!
