### ISSUE TITLE
Multiprocess (e10s) Compatibility ?

### ISSUE THREAD

**Issue by physkets** [tosdr/tosdr-firefox#37]

**Comment by AbdullahDiaa** [comment]
@physkets Please check out webExtensions branch
https://github.com/tosdr/tosdr-firefox/tree/webExtensions

The new update will be soon in AMO, will keep you updated

**Comment by AbdullahDiaa** [comment]
https://addons.mozilla.org/en-US/firefox/addon/terms-of-service-didnt-read/versions/beta
