### ISSUE TITLE
WebExtensions compatibility

### ISSUE THREAD

**Issue by erkinalp** [tosdr/tosdr-firefox#39]

**Comment by yfdyh000** [comment]
Load the https://github.com/tosdr/tosdr-chrome/tree/master/app looks work.

**Comment by erkinalp** [comment]
Chrome addon will not pass AMO's self-distribution signing. It reports banned third party JS library.

**Comment by yfdyh000** [comment]
FYI:
https://github.com/mozilla/addons-linter/blob/master/docs/third-party-libraries.md 
https://github.com/tosdr/tosdr-chrome/blob/master/app/libs/jquery.js 
"jQuery JavaScript Library v1.7.2"

https://github.com/mozilla/amo-validator/blob/master/validator/testcases/hashes-allowed.txt (may be older).

**Comment by sabret00the** [comment]
Any update on getting the WebExtension released on AMO?

**Comment by AbdullahDiaa** [comment]
@sabret00the I've just started working on it, stay tuned 😃 
https://github.com/tosdr/tosdr-firefox/tree/webExtensions

**Comment by sabret00the** [comment]
Fantastic news. Thanks for your hard work @AbdullahDiaa

**Comment by AbdullahDiaa** [comment]
@pwd-github 
You can now try the addon
https://addons.mozilla.org/en-US/firefox/addon/terms-of-service-didnt-read/versions/beta

**Comment by pwd-github** [comment]
Thank you @AbdullahDiaa
