### ISSUE TITLE
Support in Firefox 57

### ISSUE THREAD

**Issue by zanedb** [tosdr/tosdr-firefox#46]
In case you are not aware, in Firefox 57 ToS;DR is no longer supported. [Here](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing) is an article about it.

Do you plan to support this?

**Comment by yfdyh000** [comment]
Dupe of #39.

**Comment by zanedb** [comment]
Sorry, didn't see. Thanks, I hope it's ready soon.

**Comment by skddc** [comment]
I think it's pretty obviously confusing to everyone that the Web Extension has not been published as proper stable release yet, however all open issues about it are being closed (thus invisible to people arriving here). So it always looks like it's just outdated.

Maybe add a note to the README about it or something? I'd also create an issue with the necessary tasks that are left to do before publishing the extension. Or, if there aren't any, just publish it right away and fix potential issues in upcoming patch releases.

Sorry for just jumping in like this with my comment, but I keep seeing these issues being opened, and I also just heard someone say "ToS;DR is not maintained anymore" in a conference talk the other day. So just want to point out that the situation could be communicated a bit better to your users. ;)

**Comment by AbdullahDiaa** [comment]
@skddc addon 0.6 version has been already submitted and awaiting review.

**Comment by paanvaannd** [comment]
@AbdullahDiaa Any news on the submission? This add-on is great and I look forward to using it again with FF 57+ :+)

**Comment by hugoroy** [comment]
↪ Pavan Anand / novembre 11, 2017 1:17:
> @AbdullahDiaa Any news on the submission? This add-on is great and I look forward to using it again with FF 57+ :+)

Yes:

https://addons.mozilla.org/en-US/firefox/addon/terms-of-service-didnt-read/versions/beta

**Comment by AbdullahDiaa** [comment]
@paanvaannd @hugoroy Addon security bug has been fixed and resubmitted to AMO 0.6.1.

**Comment by AbdullahDiaa** [comment]
@paanvaannd @hugoroy  Finally addon approved and live now 🚀
https://addons.mozilla.org/en-US/firefox/addon/terms-of-service-didnt-read/
