### ISSUE TITLE
Note check should be either lazy or throttled on the browser scale

### ISSUE THREAD

**Issue by Porkepix** [tosdr/tosdr-firefox#47]
Tested with latest version from AMO on Firefox Nightly.

With the current addon, at the install time or when user is (re)starting its browser with many tabs, it is checking the note and informations for every single tab, loaded or not, foreground or not.

For heavy tab users like me (hundreds if not thousands of tabs) this is clearly hurting browser's performances the time it is doing it.
Note check should be either lazy and loaded once the tab go on foreground or throttled for all tabs on a global scale.

EDIT: Other browsers might be affected by the same issue, I didn't check. However I guess those are less exposed to heavy tab users due to the amount of memory used.

**Comment by AbdullahDiaa** [comment]
@Porkepix fixed in 0.6.2 
https://addons.mozilla.org/en-US/firefox/addon/terms-of-service-didnt-read/versions/beta?page=1#version-0.6.2pre1

**Comment by AbdullahDiaa** [comment]
@Porkepix Do you face the same problem with 0.6.2pre1?

**Comment by Porkepix** [comment]
Sorry, I thought you would release it directly.
So, I installed your 0.6.2 beta, and it looks way better yeah, Firefox seems to be back to a normal restart time, thanks :)

(I guess that something in theory possible to have load of unloaded tabs a little bit faster would be to load them progressively after browser finished to load… but I thin it would be kinda difficult if not impossible, and anyway probably not worth the effort)
