### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by roipoussiere** [tosdr/tosdr-firefox#48]
When I click on the ToSDR button from a non-rated website a popup "Non rated yet" appears with a button "Contribute". When I click on it, I get a "SSL_ERROR_INTERNAL_ERROR_ALERT":

![screenshot at 2018-01-09 10 47 33](https://user-images.githubusercontent.com/1665542/34715057-a404aeda-f52b-11e7-97ee-afd63d847d9d.png)

**Comment by skddc** [comment]
Could you click "en savoir plus..." and post a screenshot of that, please? It will contain the actual SSL error that you're encountering.

**Comment by roipoussiere** [comment]
The link points to a [generic page](https://support.mozilla.org/fr/kb/que-signifie-votre-connexion-nest-pas-securisee), which doesn't give additional information about this error in particular.

The contribute button points to https://edit.tosdr.org/.

When open this link on Chrome I get an other error:

```
ERR_SSL_PROTOCOL_ERROR
```

With wget I get:

```
Connexion à edit.tosdr.org (edit.tosdr.org)|54.228.209.251|:443… connecté.
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Incapable d'établir une connexion SSL.
```

and curl:

```
curl: (35) gnutls_handshake() failed: Internal error
```

**Comment by hugoroy** [comment]
we are currently moving edit.tosdr.org to our new platform, this may 
explain the error and should be temporary

@michielbdejong?

**Comment by michielbdejong** [comment]
Yes, that's the reason. Sorry, I wasn't aware that we were linking to it from the plugin. I'll fix the SSL error and put up a holding page.

**Comment by michielbdejong** [comment]
fixed, thanks for reporting!
