### ISSUE TITLE
No rate

### ISSUE THREAD

**Issue by floSoX** [tosdr/tosdr-firefox#51]
No rate with v0.6.2 under Windows and Debian with Firefox 60.

An example with Youtube:
![image](https://user-images.githubusercontent.com/1256948/41499874-9fe0749a-7188-11e8-89ef-38932e83c771.png)

Tell me what kind of information can I provide to help you.

Regards,

**Comment by floSoX** [comment]
Under the same conditions, it's now working :-)
![image](https://user-images.githubusercontent.com/1256948/42876680-b5c10578-8a87-11e8-949c-be5f407f9b28.png)

**Comment by michielbdejong** [comment]
Great! I restored some legacy fields in the JSON api which the plugin still uses, so good to hear that that had the desired effect :)
