### ISSUE TITLE
Option to not send anything to the server until user requests it

### ISSUE THREAD

**Issue by aleksejrs** [tosdr/tosdr-firefox#62]
Am I correct that the extension sends every domain you visit to tosdr.org?

There is no option to delay it until the user asks for that to be done. Not only is that bad for privacy, it may have taken issue #47 back to life when Firefox changed the way it saves RAM.

**Comment by michielbdejong** [comment]
No, we thought of that. :) To avoid leaking your browser history to the server, it simply downloads the entire list of reviews.

**Comment by aleksejrs** [comment]
Oh, cool! `browser-extension-data/jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack/storage.js`
